import os, shutil, platform

env = Environment()
env.Append( ENV = {'PATH' : os.environ['PATH'] })


if(platform.system() == "Linux"):
    env.Append( CPPFLAGS = '-fPIC -Wall -pedantic -pthread -std=c++14' )
    env.Append( LINKFLAGS = '-Wall -pthread' )
    env.Append( LIBS = [  ] )

elif(platform.system() == "Windows"):
   env.Append( CPPPATH = [ Dir('C:/Boost/include/boost-1_57'), #tutaj zainstalowane naglowki boost
                           Dir('C:/Python27/include') ] ) #tutaj zaistalowane naglowki python
   env.Append( LIBPATH = [ Dir('C:/Boost/lib'), #tutaj sciezka do bibliotek boost
                           Dir('C:/Python27/libs') ] ) #tutaj sciezki do bibliotek python

   env.Append( CPPFLAGS = ' /EHsc /MD /D "WIN32" /D "_CONSOLE" /W4' )
   env.Append( LINKFLAGS = ' /SUBSYSTEM:CONSOLE ' )
else:
   print platform.system() + " not supported"

env.Program('test', ['test.cpp', 'Game.cpp', 'GameList.cpp'])
